//! Python bindings for Route.

use crate::extract_layer;
use crate::geometry::PyPoint;
use crate::layout::{PyCell, PyPort};
use pyo3::exceptions::{PyTypeError, PyValueError};
use pyo3::prelude::*;
use pyo3::types::{PyList, PyTuple};
use rosette_route::{BendInfo, BendProfile, Route, RouteBuildError, RouteResult};
use std::f64::consts::PI;
use std::panic::{AssertUnwindSafe, catch_unwind};

fn positive_finite(name: &str, value: f64) -> PyResult<()> {
    let max_safe_value = f64::MAX.sqrt() / 4.0;
    if !value.is_finite() || value <= 0.0 || value > max_safe_value {
        return Err(PyValueError::new_err(format!(
            "{name} must be positive and finite and within the route geometry range"
        )));
    }
    Ok(())
}

fn finite_position(x: f64, y: f64) -> PyResult<()> {
    let max_safe_coordinate = f64::MAX.sqrt() / 4.0;
    if !x.is_finite()
        || !y.is_finite()
        || x.abs() > max_safe_coordinate
        || y.abs() > max_safe_coordinate
    {
        return Err(PyValueError::new_err(
            "Route waypoint coordinates must be finite within the route geometry range",
        ));
    }
    Ok(())
}

fn angle_radians(angle: f64) -> PyResult<f64> {
    let radians = angle * PI / 180.0;
    if !angle.is_finite() || !radians.is_finite() {
        return Err(PyValueError::new_err("Route angle must be finite"));
    }
    Ok(radians)
}

fn validate_port(port: &PyPort) -> PyResult<()> {
    finite_position(port.0.position.x, port.0.position.y)?;
    let direction_length = port.0.direction.length();
    if !port.0.direction.is_finite() || direction_length == 0.0 || !direction_length.is_finite() {
        return Err(PyValueError::new_err(
            "Route port direction must be finite and nonzero",
        ));
    }
    if let Some(width) = port.0.width {
        positive_finite("Route port width", width)?;
    }
    Ok(())
}

fn route_generation_error() -> PyErr {
    PyValueError::new_err("Route geometry generation produced invalid or non-finite geometry")
}

fn generated_route(route: &Route) -> PyResult<Option<RouteResult>> {
    match catch_unwind(AssertUnwindSafe(|| route.build())).map_err(|_| route_generation_error())? {
        Ok(result) => Ok(Some(result)),
        Err(RouteBuildError::InsufficientPoints { .. }) => Ok(None),
    }
}

fn build_route(route: &Route) -> PyResult<RouteResult> {
    generated_route(route)?.ok_or_else(route_generation_error)
}

fn validate_generated_route(route: &Route) -> PyResult<()> {
    let Some(result) = generated_route(route)? else {
        return Ok(());
    };
    if !result.path_length().is_finite()
        || result
            .polygons()
            .iter()
            .flat_map(|polygon| polygon.vertices())
            .any(|point| !point.is_finite())
    {
        return Err(route_generation_error());
    }
    Ok(())
}

/// Parse a `bend_profile` string from Python into the Rust enum.
fn parse_bend_profile(s: &str) -> PyResult<BendProfile> {
    match s {
        "circular" => Ok(BendProfile::Circular),
        "euler" => Ok(BendProfile::Euler),
        other => Err(PyValueError::new_err(format!(
            "bend_profile must be 'circular' or 'euler', got {other:?}"
        ))),
    }
}

/// Immutable information about a bend generated by a route.
#[pyclass(name = "BendInfo", frozen, from_py_object)]
#[derive(Clone)]
pub struct PyBendInfo(pub BendInfo);

#[pymethods]
impl PyBendInfo {
    /// Effective bend radius after any automatic reduction.
    #[getter]
    fn radius(&self) -> f64 {
        self.0.radius()
    }

    /// Bend corner/waypoint in the route cell's local coordinates.
    #[getter]
    fn position(&self) -> PyPoint {
        PyPoint(self.0.position())
    }

    /// Original requested radius when the bend was automatically reduced.
    #[getter]
    fn requested_radius(&self) -> Option<f64> {
        self.0.requested_radius()
    }

    fn __repr__(&self) -> String {
        format!(
            "BendInfo(radius={}, position=({}, {}), requested_radius={:?})",
            self.0.radius(),
            self.0.position().x,
            self.0.position().y,
            self.0.requested_radius()
        )
    }
}

/// A path-based waveguide route.
///
/// Routes generate continuous waveguide geometry from a series of waypoints,
/// automatically inserting bends at corners and interpolating width across segments.
///
/// Example:
///     route = Route(Layer(1, 0), width=0.5, bend_radius=5.0)
///     route.start_at(0, 0, angle=0)
///     route.to(50, 0)
///     route.to(50, 30)
///     route.end_at(100, 30, angle=0)
///     cell = route.to_cell("my_route")
#[pyclass(name = "Route")]
pub struct PyRoute {
    route: Route,
}

#[pymethods]
impl PyRoute {
    /// Create a new Route.
    ///
    /// Args:
    ///     layer: The layer for the route geometry
    ///     width: Default waveguide width (default: 0.5)
    ///     bend_radius: Default bend radius at corners (default: 5.0)
    ///     bend_profile: Corner bend shape — "circular" (constant radius arc) or
    ///         "euler" (clothoid, linearly varying curvature). "euler" gives a
    ///         smoother transition at the cost of a longer fillet; the
    ///         specified bend_radius is interpreted as the *minimum* radius
    ///         of curvature, reached at the corner midpoint. Default: "circular".
    #[new]
    #[pyo3(signature = (layer, width=0.5, bend_radius=5.0, bend_profile="circular"))]
    fn new(
        layer: &Bound<'_, PyAny>,
        width: f64,
        bend_radius: f64,
        bend_profile: &str,
    ) -> PyResult<Self> {
        let layer = extract_layer(layer)?;

        positive_finite("width", width)?;
        positive_finite("bend_radius", bend_radius)?;
        let profile = parse_bend_profile(bend_profile)?;

        let route = Route::new(layer)
            .with_width(width)
            .with_bend_radius(bend_radius)
            .with_bend_profile(profile);

        Ok(PyRoute { route })
    }

    /// Start the route at a specific position and angle.
    ///
    /// Args:
    ///     x: X coordinate
    ///     y: Y coordinate
    ///     angle: Direction angle in degrees (0 = +X direction)
    #[pyo3(signature = (x, y, angle=0.0))]
    fn start_at(&mut self, x: f64, y: f64, angle: f64) -> PyResult<()> {
        finite_position(x, y)?;
        let angle_rad = angle_radians(angle)?;
        let mut route = self.route.clone();
        route.start_at(x, y, angle_rad);
        validate_generated_route(&route)?;
        self.route = route;
        Ok(())
    }

    /// Start the route at a port.
    ///
    /// Uses the port's position, direction, and width.
    fn start_at_port(&mut self, port: &PyPort) -> PyResult<()> {
        validate_port(port)?;
        let mut route = self.route.clone();
        route.start_at_port(&port.0);
        validate_generated_route(&route)?;
        self.route = route;
        Ok(())
    }

    /// Add a waypoint to the route.
    ///
    /// Args:
    ///     x: X coordinate
    ///     y: Y coordinate
    ///     width: Optional width override at this point. A width change is
    ///         interpolated across the full segment ending at this waypoint.
    ///     bend_radius: Optional bend radius override at this corner
    #[pyo3(signature = (x, y, width=None, bend_radius=None))]
    fn to(&mut self, x: f64, y: f64, width: Option<f64>, bend_radius: Option<f64>) -> PyResult<()> {
        finite_position(x, y)?;
        if let Some(width) = width {
            positive_finite("width", width)?;
        }
        if let Some(bend_radius) = bend_radius {
            positive_finite("bend_radius", bend_radius)?;
        }
        let mut route = self.route.clone();
        route.to_full(x, y, width, bend_radius);
        validate_generated_route(&route)?;
        self.route = route;
        Ok(())
    }

    /// End the route at a specific position and angle.
    ///
    /// Args:
    ///     x: X coordinate
    ///     y: Y coordinate
    ///     angle: Direction angle in degrees (0 = +X direction)
    #[pyo3(signature = (x, y, angle=0.0))]
    fn end_at(&mut self, x: f64, y: f64, angle: f64) -> PyResult<()> {
        finite_position(x, y)?;
        let angle_rad = angle_radians(angle)?;
        let mut route = self.route.clone();
        route.end_at(x, y, angle_rad);
        validate_generated_route(&route)?;
        self.route = route;
        Ok(())
    }

    /// End the route at a port.
    fn end_at_port(&mut self, port: &PyPort) -> PyResult<()> {
        validate_port(port)?;
        let mut route = self.route.clone();
        route.end_at_port(&port.0);
        validate_generated_route(&route)?;
        self.route = route;
        Ok(())
    }

    /// Convert the route to a Cell.
    ///
    /// Args:
    ///     name: Name for the cell
    ///
    /// Returns:
    ///     Cell containing the route geometry
    fn to_cell(&self, name: &str) -> PyResult<PyCell> {
        let (cell, annotations) = build_route(&self.route)?.into_cell_with_annotations(name);
        cell.validate().map_err(|_| route_generation_error())?;
        Ok(PyCell::from_parts(cell, annotations))
    }

    /// Get the total optical path length.
    #[getter]
    fn path_length(&self) -> PyResult<f64> {
        let length = generated_route(&self.route)?
            .map(|result| result.path_length())
            .unwrap_or_default();
        if !length.is_finite() {
            return Err(route_generation_error());
        }
        Ok(length)
    }

    /// Get warnings from route generation.
    #[getter]
    fn warnings(&self) -> PyResult<Vec<String>> {
        Ok(generated_route(&self.route)?
            .map(|result| result.warnings().to_vec())
            .unwrap_or_else(|| vec!["Route requires at least 2 points".to_string()]))
    }

    /// Get bend diagnostics from route generation.
    #[getter]
    fn bends(&self) -> PyResult<Vec<PyBendInfo>> {
        Ok(generated_route(&self.route)?
            .map(|result| result.bends().iter().cloned().map(PyBendInfo).collect())
            .unwrap_or_default())
    }

    /// Create a route through a series of waypoints.
    ///
    /// The route draws straight segments between consecutive waypoints,
    /// inserting bends at corners. You must include intermediate waypoints
    /// to create turns — two ports alone produce a straight diagonal line.
    ///
    /// Args:
    ///     *waypoints: Sequence of waypoints. Each can be:
    ///         - Port: position + width; direction used only if first/last
    ///         - Point: uses position only
    ///         - (x, y) tuple: position only
    ///     layer: The layer for the route
    ///     width: Default waveguide width (default: 0.5)
    ///     bend_radius: Default bend radius (default: 5.0)
    ///     bend_profile: "circular" or "euler" (default: "circular").
    ///
    /// Returns:
    ///     Route object
    ///
    /// Example:
    ///     route = Route.through(port_a, (50, 0), (50, 30), port_b, layer=Layer(1, 0))
    #[staticmethod]
    #[pyo3(signature = (*waypoints, layer, width=0.5, bend_radius=5.0, bend_profile="circular"))]
    fn through(
        waypoints: &Bound<'_, PyTuple>,
        layer: &Bound<'_, PyAny>,
        width: f64,
        bend_radius: f64,
        bend_profile: &str,
    ) -> PyResult<PyRoute> {
        let layer_val = extract_layer(layer)?;

        positive_finite("width", width)?;
        positive_finite("bend_radius", bend_radius)?;

        let profile = parse_bend_profile(bend_profile)?;

        let mut route = Route::new(layer_val)
            .with_width(width)
            .with_bend_radius(bend_radius)
            .with_bend_profile(profile);

        let items: Vec<Bound<'_, PyAny>> = waypoints.iter().collect();

        if items.len() < 2 {
            return Err(PyValueError::new_err(
                "Route.through() requires at least 2 waypoints",
            ));
        }

        for (i, item) in items.iter().enumerate() {
            let is_first = i == 0;
            let is_last = i == items.len() - 1;

            // Try to extract as Port
            if let Ok(port) = item.extract::<PyPort>() {
                validate_port(&port)?;
                if is_first {
                    route.start_at_port(&port.0);
                } else if is_last {
                    route.end_at_port(&port.0);
                } else {
                    // Intermediate port - just use position as waypoint
                    route.to(port.0.position.x, port.0.position.y);
                }
                continue;
            }

            // Try to extract as Point
            if let Ok(point) = item.extract::<PyPoint>() {
                finite_position(point.0.x, point.0.y)?;
                if is_first {
                    // First point without angle - use 0
                    route.start_at(point.0.x, point.0.y, 0.0);
                } else if is_last {
                    // Last point without angle - use the incoming direction
                    route.end_at(point.0.x, point.0.y, 0.0);
                } else {
                    route.to(point.0.x, point.0.y);
                }
                continue;
            }

            // Try to extract as tuple
            if let Ok(tuple) = item.extract::<Bound<'_, PyTuple>>() {
                let len = tuple.len();
                if len >= 2 {
                    let x: f64 = tuple.get_item(0)?.extract()?;
                    let y: f64 = tuple.get_item(1)?.extract()?;
                    finite_position(x, y)?;
                    let angle = if len >= 3 {
                        angle_radians(tuple.get_item(2)?.extract()?)?
                    } else {
                        0.0
                    };

                    if is_first {
                        route.start_at(x, y, angle);
                    } else if is_last {
                        route.end_at(x, y, angle);
                    } else {
                        route.to(x, y);
                    }
                    continue;
                }
            }

            // Try to extract as list [x, y] or [x, y, angle]
            if let Ok(list) = item.extract::<Bound<'_, PyList>>() {
                let len = list.len();
                if len >= 2 {
                    let x: f64 = list.get_item(0)?.extract()?;
                    let y: f64 = list.get_item(1)?.extract()?;
                    finite_position(x, y)?;
                    let angle = if len >= 3 {
                        angle_radians(list.get_item(2)?.extract()?)?
                    } else {
                        0.0
                    };

                    if is_first {
                        route.start_at(x, y, angle);
                    } else if is_last {
                        route.end_at(x, y, angle);
                    } else {
                        route.to(x, y);
                    }
                    continue;
                }
            }

            return Err(PyTypeError::new_err(format!(
                "Waypoint {} must be a Port, Point, (x, y) tuple, or [x, y] list",
                i
            )));
        }

        validate_generated_route(&route)?;
        Ok(PyRoute { route })
    }

    fn __repr__(&self) -> PyResult<String> {
        Ok(format!("Route(path_length={:.3})", self.path_length()?))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rosette_core::Layer;

    #[test]
    fn route_cell_and_bends_share_generated_annotations() {
        let mut route = Route::new(Layer::from(1));
        route.start_at(0.0, 0.0, 0.0);
        route.to(10.0, 0.0);
        route.end_at(10.0, 10.0, PI / 2.0);
        let route = PyRoute { route };

        let bends = route.bends().unwrap();
        let cell = route.to_cell("route").unwrap();

        assert_eq!(bends.len(), 1);
        assert_eq!(cell.route_annotations().bends(), &[bends[0].0.clone()]);
        assert_eq!(
            cell.route_annotations().path_length(),
            Some(route.path_length().unwrap())
        );
    }

    #[test]
    fn incomplete_route_has_empty_bend_diagnostics() {
        let route = PyRoute {
            route: Route::new(Layer::from(1)),
        };

        assert!(route.bends().unwrap().is_empty());
        assert_eq!(
            route.warnings().unwrap(),
            ["Route requires at least 2 points"]
        );
    }
}
