"""Native ``rosette._core`` extension contract.

This file describes only symbols registered by the PyO3 module. The supported
user-facing API and project agent reference live in ``rosette.api.pyi``.
"""

from collections.abc import Iterator, Sequence
from typing import Literal

class Point:
    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @staticmethod
    def origin() -> Point: ...
    def distance_to(self, /, other: Point) -> float: ...
    def translate(self, /, v: Vector2) -> Point: ...
    def rotate(self, /, angle_deg: float) -> Point: ...
    def rotate_around(self, /, center: Point, angle_deg: float) -> Point: ...
    def __add__(self, other: Vector2) -> Point: ...
    def __sub__(self, other: Point) -> Vector2: ...

class Vector2:
    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @staticmethod
    def unit_x() -> Vector2: ...
    @staticmethod
    def unit_y() -> Vector2: ...
    @staticmethod
    def from_angle(angle_deg: float) -> Vector2: ...
    def length(self, /) -> float: ...
    def normalize(self, /) -> Vector2: ...
    def dot(self, /, other: Vector2) -> float: ...
    def perpendicular(self, /) -> Vector2: ...
    def rotate(self, /, angle_deg: float) -> Vector2: ...
    def __add__(self, other: Vector2) -> Vector2: ...
    def __sub__(self, other: Vector2) -> Vector2: ...
    def __mul__(self, scalar: float) -> Vector2: ...
    def __rmul__(self, scalar: float) -> Vector2: ...
    def __neg__(self) -> Vector2: ...

class Polygon:
    def __init__(self, vertices: list[Point]) -> None: ...
    @staticmethod
    def rect(origin: Point, width: float, height: float) -> Polygon: ...
    @staticmethod
    def rect_centered(center: Point, width: float, height: float) -> Polygon: ...
    @staticmethod
    def regular(center: Point, radius: float, sides: int) -> Polygon: ...
    def vertices(self, /) -> list[Point]: ...
    def area(self, /) -> float: ...
    def centroid(self, /) -> Point: ...
    def bbox(self, /) -> BBox: ...
    def translate(self, /, v: Vector2) -> Polygon: ...
    def rotate(self, /, angle_deg: float) -> Polygon: ...
    def rotate_around(self, /, center: Point, angle_deg: float) -> Polygon: ...
    def scale(self, /, sx: float, sy: float) -> Polygon: ...
    def mirror_x(self, /) -> Polygon: ...
    def mirror_y(self, /) -> Polygon: ...
    def union(self, /, other: Polygon) -> list[Polygon]: ...
    def subtract(self, /, other: Polygon) -> list[Polygon]: ...
    def intersect(self, /, other: Polygon) -> list[Polygon]: ...
    def xor(self, /, other: Polygon) -> list[Polygon]: ...
    def __iter__(self) -> Iterator[Point]: ...
    def __len__(self) -> int: ...

class Transform:
    def __init__(self) -> None: ...
    @staticmethod
    def identity() -> Transform: ...
    @staticmethod
    def translate(tx: float, ty: float) -> Transform: ...
    @staticmethod
    def rotate(angle_deg: float) -> Transform: ...
    @staticmethod
    def scale_uniform(s: float) -> Transform: ...
    @staticmethod
    def scale(sx: float, sy: float) -> Transform: ...
    def apply(self, /, p: Point) -> Point: ...
    def then(self, /, other: Transform) -> Transform: ...

class BBox:
    def __init__(self, min: Point, max: Point) -> None: ...
    @property
    def min(self) -> Point: ...
    @property
    def max(self) -> Point: ...
    def width(self, /) -> float: ...
    def height(self, /) -> float: ...
    def center(self, /) -> Point: ...
    def area(self, /) -> float: ...
    def contains(self, /, p: Point) -> bool: ...
    def merge(self, /, other: BBox) -> BBox: ...

class PathEndType:
    FLUSH: PathEndType
    ROUND: PathEndType
    HALF_WIDTH_EXTENSION: PathEndType

class Layer:
    def __init__(self, number: int, datatype: int = 0) -> None: ...
    @property
    def number(self) -> int: ...
    @property
    def datatype(self) -> int: ...
    def __hash__(self) -> int: ...

class Port:
    def __init__(
        self,
        name: str,
        position: Point,
        direction: Vector2,
        width: float | None = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def position(self) -> Point: ...
    @property
    def direction(self) -> Vector2: ...
    @property
    def width(self) -> float | None: ...
    def angle(self, /) -> float: ...
    def can_connect_to(self, /, other: Port, tolerance: float = 0.001) -> bool: ...

class CellRef:
    def __init__(self, cell_or_name: Cell | str) -> None: ...
    @staticmethod
    def _from_transform(cell_name: str, transform: Transform) -> CellRef: ...
    @property
    def cell_name(self) -> str: ...
    def at(self, /, x: float, y: float) -> CellRef: ...
    def rotate(self, /, angle_deg: float) -> CellRef: ...
    def mirror_x(self, /) -> CellRef: ...
    def mirror_y(self, /) -> CellRef: ...
    def scale(self, /, s: float) -> CellRef: ...
    def array(
        self, /, columns: int, rows: int, col_spacing: float, row_spacing: float
    ) -> CellRef: ...
    def array_vectors(
        self,
        /,
        columns: int,
        rows: int,
        col_vector: Vector2,
        row_vector: Vector2,
    ) -> CellRef: ...
    def port(self, /, name: str, cell: Cell) -> Port: ...

class Cell:
    def __init__(self, name: str, *, drc_skip: bool = False) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def path_length(self) -> float | None: ...
    @path_length.setter
    def path_length(self, length: float) -> None: ...
    @property
    def bends(self) -> list[dict[str, float]]: ...
    @property
    def cell_warnings(self) -> list[str]: ...
    @property
    def drc_skip(self) -> bool: ...
    @drc_skip.setter
    def drc_skip(self, drc_skip: bool) -> None: ...
    @property
    def drc_waive_regions(self) -> list[BBox]: ...
    @drc_waive_regions.setter
    def drc_waive_regions(self, regions: list[BBox]) -> None: ...
    def add_polygon(self, /, polygon: Polygon, layer: Layer | int | tuple[int, int]) -> None: ...
    def add_path(
        self,
        /,
        points: list[Point],
        width: float,
        layer: Layer | int | tuple[int, int],
        end_type: PathEndType | None = None,
    ) -> None: ...
    def add_text(
        self,
        /,
        text: str,
        position: Point,
        layer: Layer | int | tuple[int, int],
        height: float | None = None,
    ) -> None: ...
    def add_port(self, /, port: Port) -> None: ...
    def add_ref(self, /, cell_ref: CellRef) -> None: ...
    def add_bend(
        self, /, radius: float, x: float, y: float, requested_radius: float | None = None
    ) -> None: ...
    def add_warning(self, /, warning: str) -> None: ...
    def add_drc_waive_region(self, /, region: BBox) -> None: ...
    def clear_drc_waive_regions(self, /) -> None: ...
    def port(self, /, name: str) -> Port: ...
    def ports(self, /) -> list[Port]: ...
    def polygon_count(self, /) -> int: ...
    def polygons(self, /) -> list[tuple[Polygon, Layer]]: ...
    def path_count(self, /) -> int: ...
    def text_count(self, /) -> int: ...
    def ref_count(self, /) -> int: ...
    def cell_ref_names(self, /) -> list[str]: ...
    def bbox(self, /) -> BBox | None: ...
    def place_at_port(
        self, /, cell_ref: CellRef, cell_port: Port, target_port: Port
    ) -> CellRef: ...

class Library:
    def __init__(self, name: str) -> None: ...
    @property
    def name(self) -> str: ...
    def add_cell(self, /, cell: Cell) -> None: ...
    def add_cell_recursive(self, /, cell: Cell, available_cells: list[Cell]) -> None: ...
    def cell(self, /, name: str) -> Cell | None: ...
    def cells(self, /) -> list[Cell]: ...
    def top_cell(self, /) -> Cell | None: ...
    def cell_bbox(self, /, name: str) -> BBox | None: ...

class Route:
    def __init__(
        self,
        layer: Layer | int | tuple[int, int],
        width: float = 0.5,
        bend_radius: float = 5.0,
        bend_profile: Literal["circular", "euler"] = "circular",
    ) -> None: ...
    def start_at(self, /, x: float, y: float, angle: float = 0.0) -> None: ...
    def start_at_port(self, /, port: Port) -> None: ...
    def to(
        self,
        /,
        x: float,
        y: float,
        width: float | None = None,
        bend_radius: float | None = None,
    ) -> None: ...
    def end_at(self, /, x: float, y: float, angle: float = 0.0) -> None: ...
    def end_at_port(self, /, port: Port) -> None: ...
    def to_cell(self, /, name: str) -> Cell: ...
    @property
    def path_length(self) -> float: ...
    @property
    def warnings(self) -> list[str]: ...
    @staticmethod
    def through(
        *waypoints: Port | Point | tuple[float, float] | tuple[float, float, float],
        layer: Layer | int | tuple[int, int],
        width: float = 0.5,
        bend_radius: float = 5.0,
        bend_profile: Literal["circular", "euler"] = "circular",
    ) -> Route: ...

class DrcRules:
    def __init__(self) -> None: ...
    def min_width(
        self, /, layer: Layer | int | tuple[int, int], width: float, name: str | None = None
    ) -> DrcRules: ...
    def min_spacing(
        self,
        /,
        layer1: Layer | int | tuple[int, int],
        layer2: Layer | int | tuple[int, int],
        spacing: float,
        name: str | None = None,
    ) -> DrcRules: ...
    def min_area(
        self, /, layer: Layer | int | tuple[int, int], area: float, name: str | None = None
    ) -> DrcRules: ...
    def min_enclosure(
        self,
        /,
        inner: Layer | int | tuple[int, int],
        outer: Layer | int | tuple[int, int],
        enclosure: float,
        name: str | None = None,
    ) -> DrcRules: ...
    def require_overlap(
        self,
        /,
        layer1: Layer | int | tuple[int, int],
        layer2: Layer | int | tuple[int, int],
        name: str | None = None,
    ) -> DrcRules: ...
    def forbid_overlap(
        self,
        /,
        layer1: Layer | int | tuple[int, int],
        layer2: Layer | int | tuple[int, int],
        name: str | None = None,
    ) -> DrcRules: ...
    def allowed_angles(
        self,
        /,
        layer: Layer | int | tuple[int, int],
        angles: list[float],
        name: str | None = None,
    ) -> DrcRules: ...
    def min_edge_length(
        self, /, layer: Layer | int | tuple[int, int], length: float, name: str | None = None
    ) -> DrcRules: ...
    def no_self_intersection(
        self, /, layer: Layer | int | tuple[int, int], name: str | None = None
    ) -> DrcRules: ...
    def max_width(
        self, /, layer: Layer | int | tuple[int, int], width: float, name: str | None = None
    ) -> DrcRules: ...
    def snap_to_grid(
        self,
        /,
        layer: Layer | int | tuple[int, int],
        grid_pitch: float,
        name: str | None = None,
    ) -> DrcRules: ...
    def acute_angle(
        self,
        /,
        layer: Layer | int | tuple[int, int],
        threshold_deg: float,
        name: str | None = None,
    ) -> DrcRules: ...
    def not_inside(
        self,
        /,
        inner: Layer | int | tuple[int, int],
        outer: Layer | int | tuple[int, int],
        name: str | None = None,
    ) -> DrcRules: ...
    def density(
        self,
        /,
        layer: Layer | int | tuple[int, int],
        window: float,
        step: float,
        min: float | None = None,
        max: float | None = None,
        region_layer: Layer | int | tuple[int, int] | None = None,
        name: str | None = None,
    ) -> DrcRules: ...
    def warning_margin(self, /, margin: float) -> DrcRules: ...

class DrcViolation:
    @property
    def rule_name(self) -> str | None: ...
    @property
    def message(self) -> str: ...
    @property
    def severity(self) -> str: ...
    @property
    def rule_type(self) -> str: ...
    @property
    def layer(self) -> tuple[int, int]: ...
    @property
    def layer2(self) -> tuple[int, int] | None: ...
    @property
    def bbox(self) -> tuple[tuple[float, float], tuple[float, float]]: ...
    @property
    def cell_name(self) -> str | None: ...
    @property
    def cell_name2(self) -> str | None: ...

class DrcResult:
    @property
    def violations(self) -> list[DrcViolation]: ...
    @property
    def passed(self) -> bool: ...
    @property
    def polygons_checked(self) -> int: ...
    @property
    def rules_checked(self) -> int: ...
    @property
    def elapsed_ms(self) -> float: ...
    @property
    def error_count(self) -> int: ...
    @property
    def warning_count(self) -> int: ...
    @property
    def suppressed_violations(self) -> int: ...
    @property
    def skipped_cells(self) -> int: ...
    @property
    def waived_violations(self) -> int: ...
    def __len__(self) -> int: ...

class DrcCache:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def clear(self, /) -> None: ...

class DfmConfig:
    def __init__(
        self,
        resolution: float = 0.01,
        padding: float = 1.0,
        contour_threshold: float = 0.5,
        keep_raster: bool = False,
        max_area_deviation: float | None = None,
        severity: str = "error",
    ) -> None: ...
    @property
    def resolution(self) -> float: ...
    @property
    def padding(self) -> float: ...
    @property
    def contour_threshold(self) -> float: ...
    @property
    def keep_raster(self) -> bool: ...
    @property
    def max_area_deviation(self) -> float | None: ...
    @property
    def has_tolerances(self) -> bool: ...
    def set_layer_config(
        self,
        /,
        layer: Layer | int | tuple[int, int],
        sigma: float | None = None,
        max_area_deviation: float | None = None,
        severity: str | None = None,
    ) -> None: ...

class GaussianModel:
    def __init__(self, sigma: float) -> None: ...
    @property
    def sigma(self) -> float: ...
    @property
    def name(self) -> str: ...

class LayerMetrics:
    @property
    def layer(self) -> tuple[int, int]: ...
    @property
    def max_edge_deviation(self) -> float: ...
    @property
    def area_deviation(self) -> float: ...
    @property
    def designed_area(self) -> float: ...
    @property
    def predicted_area(self) -> float: ...
    @property
    def designed_feature_count(self) -> int: ...
    @property
    def predicted_feature_count(self) -> int: ...

class DfmViolation:
    @property
    def layer(self) -> tuple[int, int]: ...
    @property
    def violation_type(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def severity(self) -> str: ...
    @property
    def bbox(self) -> tuple[tuple[float, float], tuple[float, float]]: ...
    @property
    def max_allowed(self) -> float | None: ...
    @property
    def actual(self) -> float | None: ...
    @property
    def designed_count(self) -> int | None: ...
    @property
    def predicted_count(self) -> int | None: ...

class LayerPrediction:
    @property
    def layer(self) -> tuple[int, int]: ...
    @property
    def predicted_polygons(self) -> list[Polygon]: ...
    @property
    def input_polygon_count(self) -> int: ...
    @property
    def predicted_polygon_count(self) -> int: ...
    @property
    def metrics(self) -> LayerMetrics | None: ...
    @property
    def violations(self) -> list[DfmViolation]: ...
    @property
    def has_raster(self) -> bool: ...
    @property
    def raster_data(self) -> list[float] | None: ...
    @property
    def raster_width(self) -> int | None: ...
    @property
    def raster_height(self) -> int | None: ...
    @property
    def raster_origin(self) -> tuple[float, float] | None: ...

class DfmResult:
    @property
    def layers(self) -> list[LayerPrediction]: ...
    @property
    def total_predicted_polygons(self) -> int: ...
    @property
    def total_input_polygons(self) -> int: ...
    @property
    def passed(self) -> bool: ...
    @property
    def violations(self) -> list[DfmViolation]: ...
    @property
    def layers_processed(self) -> int: ...
    @property
    def total_pixels(self) -> int: ...
    @property
    def resolution(self) -> float: ...
    @property
    def elapsed_ms(self) -> float: ...
    def __len__(self) -> int: ...

class ChecksConfig:
    def __init__(
        self,
        position_tolerance: float = 0.001,
        angle_tolerance: float = 0.1,
        check_widths: bool = True,
        min_bend_radius: float | None = None,
        severity: str = "error",
    ) -> None: ...

class CheckViolation:
    @property
    def violation_type(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def cell_path(self) -> str: ...
    @property
    def partner_name(self) -> str | None: ...
    @property
    def partner_path(self) -> str | None: ...
    @property
    def message(self) -> str: ...
    @property
    def severity(self) -> str: ...
    @property
    def bbox(self) -> tuple[tuple[float, float], tuple[float, float]]: ...

class ChecksResult:
    @property
    def passed(self) -> bool: ...
    @property
    def violations(self) -> list[CheckViolation]: ...
    @property
    def ports_checked(self) -> int: ...
    @property
    def connections_found(self) -> int: ...
    @property
    def bends_checked(self) -> int: ...
    @property
    def elapsed_ms(self) -> float: ...
    def __len__(self) -> int: ...

class RenderResult:
    @property
    def png(self) -> bytes: ...
    @property
    def view(self) -> dict[str, object]: ...
    @property
    def layers_rendered(self) -> list[tuple[int, int]]: ...
    def px_to_world(self, /, px: float, py: float) -> tuple[float, float]: ...
    def world_to_px(self, /, x: float, y: float) -> tuple[float, float]: ...

def read_gds(path: str) -> Library: ...
def write_gds(
    path: str,
    design: Cell | Library,
    cells: list[Cell] | None = None,
    quiet: bool = False,
    verbose: bool = False,
) -> None: ...
def to_json(design: Cell | Library, cells: list[Cell] | None = None) -> str: ...
def render_png(
    library: Library,
    *,
    bbox: BBox | None = None,
    cell: str | None = None,
    layers: list[tuple[int, int]] | None = None,
    width: int = 1024,
    height: int | None = None,
    pad: float = 0.1,
    bg: str = "#1a1a1a",
    fill_alpha: int = 178,
    palette: dict[int, str] | None = None,
) -> RenderResult: ...
def run_checks(
    cell: Cell, config: ChecksConfig | None = None, library: Library | None = None
) -> ChecksResult: ...
def run_drc(
    cell: Cell,
    rules: DrcRules,
    library: Library | None = None,
    cache: DrcCache | None = None,
) -> DrcResult: ...
def run_dfm(
    cell: Cell,
    layers: Sequence[Layer | int | tuple[int, int]],
    model: GaussianModel,
    config: DfmConfig | None = None,
    library: Library | None = None,
) -> DfmResult: ...
def connect_transform(component_port: Port, target_port: Port) -> Transform: ...
def arc_points(
    center: Point,
    radius: float,
    start_angle: float,
    end_angle: float,
    num_points: int = 64,
) -> list[Point]: ...
def offset_polygon(centerline: list[Point], width: float) -> Polygon: ...
def offset_polygon_varying(centerline: list[Point], widths: list[float]) -> Polygon: ...
def path_length(points: list[Point]) -> float: ...
def fresnel_c(t: float) -> float: ...
def fresnel_s(t: float) -> float: ...
