/**
 * Path/waveguide measurement utilities.
 *
 * Stored and preview ribbon geometry is generated by the canonical Rust
 * path stroker through WASM.
 */

interface Point {
  x: number;
  y: number;
}

/**
 * Angle threshold (in degrees) for Manhattan snapping.
 * Snap to H/V if within this angle of an axis.
 */
const MANHATTAN_SNAP_ANGLE_DEG = 8;

/**
 * Constrain a point to Manhattan (horizontal or vertical) movement
 * from a reference point. Only snaps if the angle is within
 * MANHATTAN_SNAP_ANGLE_DEG of an axis; otherwise returns the original
 * point for free-form diagonal movement.
 *
 * @param lastPoint - The reference point to constrain from.
 * @param currentPoint - The point to constrain.
 * @returns Point constrained to H/V if near an axis, otherwise unchanged.
 */
export function constrainToManhattan(lastPoint: Point, currentPoint: Point): Point {
  const dx = currentPoint.x - lastPoint.x;
  const dy = currentPoint.y - lastPoint.y;

  if (dx === 0 && dy === 0) return currentPoint;

  const angleFromHorizontal = Math.abs(Math.atan2(Math.abs(dy), Math.abs(dx)) * (180 / Math.PI));

  if (angleFromHorizontal <= MANHATTAN_SNAP_ANGLE_DEG) {
    return { x: currentPoint.x, y: lastPoint.y };
  }

  if (angleFromHorizontal >= 90 - MANHATTAN_SNAP_ANGLE_DEG) {
    return { x: lastPoint.x, y: currentPoint.y };
  }

  return currentPoint;
}

/**
 * Compute the total path length of a polyline (sum of Euclidean segment distances).
 *
 * When `cornerRadius > 0`, the length accounts for corner rounding: straight
 * segments are shortened by bend setbacks, and arc lengths (`radius * |turn_angle|`)
 * are added for each corner. This matches the Rust `Route.calculate_path_length()`
 * algorithm.
 *
 * Waypoints are in world coordinates. The returned length is also in world
 * coordinates — divide by `GRID_SIZE` to get nanometers.
 *
 * @param waypoints - Centerline waypoints.
 * @param cornerRadius - Bend radius in world units (0 = straight-line length).
 * @returns Total path length in world units.
 */
export function computePathLength(waypoints: Point[], cornerRadius: number = 0): number {
  const n = waypoints.length;
  if (n < 2) return 0;

  // Simple polyline length when no corner radius
  if (cornerRadius <= 0 || n < 3) {
    let length = 0;
    for (let i = 1; i < n; i++) {
      const dx = waypoints[i].x - waypoints[i - 1].x;
      const dy = waypoints[i].y - waypoints[i - 1].y;
      length += Math.sqrt(dx * dx + dy * dy);
    }
    return length;
  }

  // Pre-compute segment lengths
  const segLengths: number[] = [];
  for (let i = 0; i < n - 1; i++) {
    const dx = waypoints[i + 1].x - waypoints[i].x;
    const dy = waypoints[i + 1].y - waypoints[i].y;
    segLengths.push(Math.sqrt(dx * dx + dy * dy));
  }

  const numCorners = n - 2;

  // Compute turn angles and ideal setbacks
  const turnAngles: (number | null)[] = [];
  for (let i = 1; i < n - 1; i++) {
    const prev = waypoints[i - 1];
    const curr = waypoints[i];
    const next = waypoints[i + 1];

    const inLen = segLengths[i - 1];
    const outLen = segLengths[i];
    if (inLen < 1e-10 || outLen < 1e-10) {
      turnAngles.push(null);
      continue;
    }

    const inX = (curr.x - prev.x) / inLen;
    const inY = (curr.y - prev.y) / inLen;
    const outX = (next.x - curr.x) / outLen;
    const outY = (next.y - curr.y) / outLen;

    const cross = inX * outY - inY * outX;
    const dot = inX * outX + inY * outY;
    const turnAngle = Math.atan2(cross, dot);

    turnAngles.push(Math.abs(turnAngle) < 1e-6 ? null : turnAngle);
  }

  const setbacks: number[] = turnAngles.map((ta) => {
    if (ta === null) return 0;
    return cornerRadius * Math.tan(Math.abs(ta) / 2);
  });

  // Resolve conflicts on shared segments (iterative)
  for (let iteration = 0; iteration < 3; iteration++) {
    for (let k = 0; k < segLengths.length; k++) {
      const capacity = segLengths[k] * 0.95;
      const outCorner = k > 0 ? k - 1 : null;
      const inCorner = k < numCorners ? k : null;

      const outClaim = outCorner !== null ? setbacks[outCorner] : 0;
      const inClaim = inCorner !== null ? setbacks[inCorner] : 0;

      const total = outClaim + inClaim;
      if (total > capacity && total > 1e-10) {
        const scale = capacity / total;
        if (outCorner !== null) {
          setbacks[outCorner] = Math.min(setbacks[outCorner], outClaim * scale);
        }
        if (inCorner !== null) {
          setbacks[inCorner] = Math.min(setbacks[inCorner], inClaim * scale);
        }
      }
    }
  }

  // Sum: straight segments minus setbacks, plus arc lengths
  let length = 0;
  for (let i = 0; i < segLengths.length; i++) {
    length += segLengths[i];
  }

  for (let c = 0; c < numCorners; c++) {
    const ta = turnAngles[c];
    if (ta === null) continue;

    const halfAngle = Math.abs(ta) / 2;
    const tanHalf = Math.tan(halfAngle);
    if (Math.abs(tanHalf) < 1e-10) continue;

    const actualRadius = setbacks[c] / tanHalf;

    // Subtract setback from incoming and outgoing segments
    length -= setbacks[c] * 2;
    // Add arc length
    length += actualRadius * Math.abs(ta);
  }

  return Math.max(0, length);
}

/**
 * Info about a corner where the bend radius was auto-reduced.
 */
export interface BendReduction {
  /** 1-based index of the interior corner (1 = first interior vertex). */
  cornerIndex: number;
  /** The radius the user requested (world units). */
  requested: number;
  /** The radius actually used after clamping (world units). */
  actual: number;
}

/**
 * Check which corners of a path would have their bend radius auto-reduced.
 *
 * Uses the same two-pass setback algorithm as the Rust rounded-path builder,
 * then reports corners where
 * the resulting radius is less than requested.
 *
 * @param waypoints - Centerline waypoints in world coordinates.
 * @param cornerRadius - Requested bend radius in world units.
 * @returns Array of reductions (empty if no corners were reduced).
 */
export function checkBendRadiusReductions(
  waypoints: Point[],
  cornerRadius: number,
): BendReduction[] {
  const n = waypoints.length;
  if (n < 3 || cornerRadius <= 0) return [];

  // Pre-compute segment lengths
  const segLengths: number[] = [];
  for (let i = 0; i < n - 1; i++) {
    const dx = waypoints[i + 1].x - waypoints[i].x;
    const dy = waypoints[i + 1].y - waypoints[i].y;
    segLengths.push(Math.sqrt(dx * dx + dy * dy));
  }

  const numCorners = n - 2;

  // Pass 1: compute turn angles and ideal setbacks
  const turnAngles: (number | null)[] = [];
  for (let i = 1; i < n - 1; i++) {
    const prev = waypoints[i - 1];
    const curr = waypoints[i];
    const next = waypoints[i + 1];

    const inLen = segLengths[i - 1];
    const outLen = segLengths[i];
    if (inLen < 1e-10 || outLen < 1e-10) {
      turnAngles.push(null);
      continue;
    }

    const inX = (curr.x - prev.x) / inLen;
    const inY = (curr.y - prev.y) / inLen;
    const outX = (next.x - curr.x) / outLen;
    const outY = (next.y - curr.y) / outLen;

    const cross = inX * outY - inY * outX;
    const dot = inX * outX + inY * outY;
    const turnAngle = Math.atan2(cross, dot);

    turnAngles.push(Math.abs(turnAngle) < 1e-6 ? null : turnAngle);
  }

  const setbacks: number[] = turnAngles.map((ta) => {
    if (ta === null) return 0;
    return cornerRadius * Math.tan(Math.abs(ta) / 2);
  });

  // Pass 2: resolve conflicts (iterative)
  for (let iteration = 0; iteration < 3; iteration++) {
    for (let k = 0; k < segLengths.length; k++) {
      const capacity = segLengths[k] * 0.95;
      const outCorner = k > 0 ? k - 1 : null;
      const inCorner = k < numCorners ? k : null;

      const outClaim = outCorner !== null ? setbacks[outCorner] : 0;
      const inClaim = inCorner !== null ? setbacks[inCorner] : 0;

      const total = outClaim + inClaim;
      if (total > capacity && total > 1e-10) {
        const scale = capacity / total;
        if (outCorner !== null) {
          setbacks[outCorner] = Math.min(setbacks[outCorner], outClaim * scale);
        }
        if (inCorner !== null) {
          setbacks[inCorner] = Math.min(setbacks[inCorner], inClaim * scale);
        }
      }
    }
  }

  // Report reductions
  const reductions: BendReduction[] = [];
  for (let c = 0; c < numCorners; c++) {
    const ta = turnAngles[c];
    if (ta === null) continue;

    const halfAngle = Math.abs(ta) / 2;
    const tanHalf = Math.tan(halfAngle);
    if (Math.abs(tanHalf) < 1e-10) continue;

    const actualRadius = setbacks[c] / tanHalf;
    if (actualRadius < cornerRadius - 1e-6) {
      reductions.push({
        cornerIndex: c + 1, // 1-based
        requested: cornerRadius,
        actual: actualRadius,
      });
    }
  }

  return reductions;
}

/**
 * Compute the actual minimum bend radius for a path after auto-reduction.
 *
 * Returns `cornerRadius` unchanged when no reduction is needed, or the
 * smallest effective radius across all corners when segments are too short.
 *
 * @param waypoints - Centerline waypoints in world coordinates.
 * @param cornerRadius - Requested bend radius in world units.
 * @returns The effective minimum corner radius (world units).
 */
export function computeActualCornerRadius(waypoints: Point[], cornerRadius: number): number {
  if (cornerRadius <= 0) return 0;
  const reductions = checkBendRadiusReductions(waypoints, cornerRadius);
  if (reductions.length === 0) return cornerRadius;
  return Math.min(...reductions.map((r) => r.actual));
}
